# Manupuladno Texto
frase = 'Curso em vídeo Python'
frase3 = frase.split()
print(frase[9])
print(frase[9:13])
print(frase[9:21])
print(frase[9:21:2])
print(frase[:5])
print(frase[15:])
print(frase[9::3])
print(len(frase))
print(frase.count('o'))
print(frase.count('o', 0, 13))
print(frase.find('deo'))
print(frase.find('Android'))
a = 'Curso ' in frase
print(a)
print(frase.replace('Python', 'Android'))
print(frase.upper())
print(frase.lower())
print(frase.capitalize())
print(frase.title())
frase2 = '   Aprenda Python   '
print(frase2.strip())
print(frase.split())
print('-'.join(frase3))
